services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: "no"
    environment:
      POSTGRES_USER: pagespeeduser
      POSTGRES_PASSWORD: pagespeedpassword
      POSTGRES_DB: pagespeed
    healthcheck:
      test:
        - CMD-SHELL
        - “pg_isready”
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  db_data: {}
